248.2-1ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/tests/root-unittests b/debian/tests/root-unittests
--- a/debian/tests/root-unittests
+++ b/debian/tests/root-unittests
@@ -1,6 +1,14 @@
 #!/bin/sh
 set -eu
 
+for j in /var/log/journal/*/*; do
+    echo "Verifying local journal file $j"
+    if ! journalctl --verify --file "$j"; then
+        echo "Verification failed, removing corrupt file $j"
+        rm -vf "$j"
+    fi
+done
+
 EXFAIL=""
 
 res=0
@@ -8,6 +16,12 @@ for t in /usr/lib/systemd/tests/test-*; do
     tname=$(basename $t)
     # test-udev needs special prep and has its own test
     [ "$tname" != test-udev ] || continue
+    # test-execute fails in LXC LP: #1878051
+    [ "$tname" != test-execute ] || ! systemd-detect-virt -c -q || continue
+    # test-mount-util fails in LXC, too:
+    # Assertion 'bind_remount_recursive(p, MS_RDONLY, MS_RDONLY, STRV_MAKE("/sys/kernel")) >= 0'
+    # failed at src/test/test-mount-util.c:111, function test_bind_remount_recursive(). Aborting.
+    [ "$tname" != test-mount-util ] || ! systemd-detect-virt -c -q || continue
     echo "====== $tname ======="
     # exit code 77 means "skip"
     rc=0
