237-3ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/tests/upstream b/debian/tests/upstream
--- a/debian/tests/upstream
+++ b/debian/tests/upstream
@@ -5,7 +5,7 @@ set -e
 
 # even after installing policycoreutils this fails with
 # "Failed to install /usr/libexec/selinux/hll/pp"
-BLACKLIST="TEST-06-SELINUX"
+BLACKLIST="TEST-06-SELINUX TEST-16-EXTEND-TIMEOUT"
 
 # quiesce Makefile.guess; not really relevant as systemd/nspawn run from
 # installed packages
@@ -22,19 +22,26 @@ sed -i '/@make.*all/ d' test/TEST*/Makefile
 # adjust path
 sed -i 's_/usr/libexec/selinux/hll/pp_/usr/lib/selinux/hll/pp_' test/TEST-06-SELINUX/test.sh
 
+FAILED=""
+
 for t in test/TEST*; do
     echo "$BLACKLIST" | grep -q "$(basename $t)" && continue
     echo "========== `basename $t` =========="
     rm -rf /var/tmp/systemd-test.*
     if ! make -C $t clean setup run; then
-        for j in /var/tmp/systemd-test.*/journal/*; do
+        for j in /var/tmp/systemd-test.*/journal/*/system.journal; do
             [ -e "$j" ] || continue
             # keep the entire journal in artifacts, in case one needs the debug messages
-            cp "$j" "$AUTOPKGTEST_ARTIFACTS/$(basename $t)-$(basename $j)"
+            cp "$j" "$AUTOPKGTEST_ARTIFACTS/$(basename $t)-$(basename $(dirname $j))"
             echo "---- $j ----"
-            journalctl --priority=warning --directory=$j
+            journalctl --priority=warning --file=$j
         done
-        exit 1
+        FAILED="$FAILED $t"
     fi
     echo
 done
+
+if [ -n "$FAILED" ]; then
+        echo FAILED TESTS: "$FAILED"
+        exit 1
+fi
