249.9-0ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -24,6 +24,32 @@ if [ -z "$2" ]; then
     systemctl enable remote-fs.target || true
 fi
 
+# Enable resolved by default on new installs installs and upgrades
+if dpkg --compare-versions "$2" lt "234-1ubuntu2~"; then
+    systemctl enable systemd-resolved.service || true
+fi
+
+# Drop stock /etc/rc.local on upgrades
+if dpkg --compare-versions "$2" lt "234-2ubuntu11~"; then
+        if [ -f /etc/rc.local ]; then
+                if [ "10fd9f051accb6fd1f753f2d48371890" = "$(md5sum /etc/rc.local | cut -d\  -f1)" ]; then
+                        echo Removing empty /etc/rc.local
+                        rm -f /etc/rc.local || true
+                fi
+        fi
+fi
+
+# Use stub resolve.conf by default on new installs
+if [ -z "$2" ]; then
+    mkdir -p /run/systemd/resolve
+    if [ -e /etc/resolv.conf ]; then
+            cp /etc/resolv.conf /run/systemd/resolve/stub-resolv.conf
+    fi
+    # If /etc/resolv.conf is a bind-mount, moving or replacing
+    # /etc/resolv.conf may fail
+    ln -snf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf || true
+fi
+
 # Enable systemd-pstore by default on new installs and upgrades, see #952767
 if dpkg --compare-versions "$2" lt "245.4-4~"; then
     systemctl enable systemd-pstore.service || true
@@ -40,15 +66,11 @@ adduser --quiet --system --group --no-create-home --home /run/systemd \
 adduser --quiet --system --group --no-create-home --home /run/systemd \
     --gecos "systemd Resolver" systemd-resolve
 
-# Enable persistent journal, in auto-mode, by default on new installs and upgrades
-if dpkg --compare-versions "$2" lt "244.1-2~"; then
+# Enable persistent journal, in auto-mode, by default on new installs installs and upgrades
+if dpkg --compare-versions "$2" lt "235-3ubuntu3~"; then
     mkdir -p /var/log/journal
-    # Applying ACLs requires a mounted /proc and systemd-tmpfiles will fail if
-    # /proc is not available. Skip systemd-tmpfiles in this case. This should
-    # be fine, as this typically means we are inside a chroot and systemd is
-    # not currently active. The permissions will be applied on the next boot.
-    # https://github.com/systemd/systemd/issues/14745
-    if mountpoint -q /proc; then
+    # create tmpfiles only when running systemd, otherwise %b substitution fails
+    if [ -d /run/systemd/system ]; then
         systemd-tmpfiles --create --prefix /var/log/journal
     fi
 fi
@@ -56,7 +78,15 @@ fi
 # Initial update of the Message Catalogs database
 _update_catalog
 
-if [ -n "$2" ]; then
+# Disable networkd when upgrading from broken versions 8..10. Turns out
+# enabling networkd unconditionally has long boot time side-effects
+if dpkg --compare-versions "$2" gt "234-2ubuntu8~" &&
+   dpkg --compare-versions "$2" lt "234-2ubuntu11~"; then
+    systemctl disable systemd-networkd-wait-online.service || true
+fi
+
+# skip daemon-reexec and try-restarts during shutdown to avoid hitting LP: #1803391
+if [ -n "$2" ] && [ "$(systemctl is-system-running)" != "stopping" ]; then
     _systemctl daemon-reexec || true
     # don't restart logind; this can be done again once this gets implemented:
     # https://github.com/systemd/systemd/issues/1163
@@ -68,6 +98,12 @@ if [ -n "$2" ]; then
     _systemctl try-restart systemd-resolved.service || true
     _systemctl try-restart systemd-journald.service || true
 fi
+
+# Process all tmpfiles that we ship, including any overrides in
+# runtime-dir/sysadmin-dir/other packages (e.g. rsyslog)
+#
+# Ignore if this fails, because e.g. %b will fail on WSL
+systemd-tmpfiles --create || :
 
 if dpkg --compare-versions "$2" lt-nl "245.4-4~"; then
     # systemd-pstore.service is now enabled via sysinit.target
