251.4-1ubuntu2 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/systemd-resolved.postinst b/debian/systemd-resolved.postinst
--- a/debian/systemd-resolved.postinst
+++ b/debian/systemd-resolved.postinst
@@ -25,4 +25,14 @@ if [ "$1" = configure ] && [ -z "$2" ]; then
     _adopt_conffile /etc/systemd/resolved.conf systemd-resolved
 fi
 
+if [ "$1" = configure ] && dpkg --compare-versions "$2" lt 251.4-1ubuntu2; then
+    if [ "$(readlink "/etc/resolv.conf")" != "../run/systemd/resolve/stub-resolv.conf" ] && [ "$(readlink "/etc/resolv.conf")" != "/run/systemd/resolve/stub-resolv.conf" ]; then
+        echo "Converting /etc/resolv.conf to a symlink to /run/systemd/resolve/stub-resolv.conf..."
+        if [ -f "/etc/resolv.conf" ]; then
+            mv "/etc/resolv.conf" "/etc/.resolv.conf.systemd-resolved.bak" || echo "Cannot take a backup of /etc/resolv.conf."
+        fi
+        ln -sf ../run/systemd/resolve/stub-resolv.conf "/etc/resolv.conf" || echo "Cannot install symlink from /etc/resolv.conf to ../run/systemd/resolve/stub-resolv.conf"
+    fi
+fi
+
 #DEBHELPER#
