Import patches-unapplied version 245.4-4 to debian/sid
Imported using git-ubuntu import.

Changelog parent: 1a4d6ff47429e17ad7dea3220931f4579e34a937

New changelog entries:
  * Drop Conflicts: virtualbox-guest-utils from systemd-timesyncd.
    Otherwise this could lead to virtualbox-guest-utils being uninstalled on
    upgrades which is not intended. (Closes: #956436)
  * pid1: automatically generate systemd-remount-fs.service deps, plus enable
    systemd-pstore from sysinit.target
  * Fix systemd-pstore.service enablement symlink on upgrades.
    It is now started via sysinit.target. Also clean up the symlink on
    purge.

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -40,7 +40,7 @@ if [ -e /lib/systemd/system/ondemand.service ] && [ -z "$2" ]; then
 fi
 
 # Enable systemd-pstore by default on new installs and upgrades, see #952767
-if dpkg --compare-versions "$2" lt-nl "245.4-1~"; then
+if dpkg --compare-versions "$2" lt "245.4-4~"; then
     systemctl enable systemd-pstore.service || true
 fi
 
@@ -104,10 +104,10 @@ adduser --quiet --system --group --no-create-home --home /run/systemd \
 # Enable persistent journal, in auto-mode, by default on new installs and upgrades
 if dpkg --compare-versions "$2" lt "244.1-2~"; then
     mkdir -p /var/log/journal
-    # Applying ACLs requires a mounted /proc and systemd-tmpfiles will fail if /proc is not
-    # available. Skip systemd-tmpfiles in this case. This should be fine, as this typically
-    # means we are inside a chroot and systemd is not currently active. The permissions will
-    # be applied on the next boot.
+    # Applying ACLs requires a mounted /proc and systemd-tmpfiles will fail if
+    # /proc is not available. Skip systemd-tmpfiles in this case. This should
+    # be fine, as this typically means we are inside a chroot and systemd is
+    # not currently active. The permissions will be applied on the next boot.
     if mountpoint -q /proc; then
         systemd-tmpfiles --create --prefix /var/log/journal
     fi
@@ -142,6 +142,12 @@ if dpkg --compare-versions "$2" lt-nl "239-12~"; then
     if getent group nobody >/dev/null; then
         delgroup --system nobody || true
     fi
+fi
+
+if dpkg --compare-versions "$2" lt-nl "245.4-4~"; then
+    # systemd-pstore.service is now enabled via sysinit.target
+    rm -f /etc/systemd/system/systemd-remount-fs.service.wants/systemd-pstore.service
+    rmdir --ignore-fail-on-non-empty /etc/systemd/system/systemd-remount-fs.service.wants 2> /dev/null || true
 fi
 
 #DEBHELPER#
