Import patches-unapplied version 215-1 to debian/experimental
Imported using git-ubuntu import.

Changelog parent: 1dc9ac44e8d299455d9902c9dd6f650190fe1e0e

New changelog entries:
  * New upstream release.
  * Import upstream v215-stable patch series.
  * Rebase remaining Debian patches on top of v215-stable.
  * Drop our Debian-specific run-user.mount unit as upstream now creates a
    per-user tmpfs via logind.
  * Don't rely on new mount from experimental for now and re-add the patch
    which updates the documentation accordingly.
  * Cherry-pick upstream fix to use correct versions for the new symbols that
    were introduced in libudev.
  * Update symbols files
    - Add two new symbols for libudev1.
    - Remove private symbol from libgudev-1.0-0. This symbol was never part of
      the public API and not used anywhere so we don't need a soname bump.
  * Cherry-pick upstream commit to not install busname units if kdbus support
    is disabled.
  * Make /run/lock tmpfs an API fs so it is available during early boot.
    (Closes: #751392)
  * Install new systemd-path and systemd-escape binaries.
  * Cherry-pick upstream commit which fixes the references to the systemctl
    man page. (Closes: #760613)
  * Use the new systemd-escape utility to properly escape the network
    interface name when starting an ifup@.service instance for hotplugged
    network interfaces. Make sure a recent enough systemd version is installed
    by bumping the versioned Breaks accordingly. (Closes: #747044)
  * Order ifup@.service after networking.service so we don't need to setup the
    runtime directory ourselves and we have a defined point during boot when
    hotplugged network interfaces are started.
  * Disable factory-reset feature and remove files associated with it. This
    feature needs more integration work first before it can be enabled in
    Debian.
  * Cherry-pick upstream commit to fix ProtectSystem=full and make the
    ProtectSystem= option consider /bin, /sbin, /lib and /lib64 (if it exists)
    on Debian systems. (Closes: #759689)
  * Use adduser in quiet mode when creating the system users/groups to avoid
    warning messages about the missing home directories. Those are created
    dynamically during runtime. (Closes: #759175)
  * Set the gecos field when creating the system users.
  * Add systemd-bus-proxy system user so systemd-bus-proxyd can properly drop
    its privileges.
  * Re-exec systemd and restart services at the end of postinst.
  * Cherry-pick upstream commit for sd-journal to properly convert
    object->size on big endian which fixes a crash in journalctl --list-boots.
    (Closes: #758392)

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -33,15 +33,6 @@ if dpkg --compare-versions "$2" lt "204-1"; then
     rm -f /var/lib/systemd/*.symlinks
 fi
 
-if [ -n "$2" ]; then
-    _systemctl daemon-reexec || true
-    _systemctl try-restart systemd-journald.service || true
-    _systemctl try-restart systemd-logind.service || true
-    _systemctl try-restart systemd-networkd.service || true
-    _systemctl try-restart systemd-resolved.service || true
-    _systemctl try-restart systemd-timesyncd.service || true
-fi
-
 # Do a one-time migration of the local time setting
 if dpkg --compare-versions "$2" lt "33-1"; then
     if [ -f /etc/default/rcS ]; then
@@ -100,45 +91,52 @@ if dpkg --compare-versions "$2" lt "40-1"; then
     fi
 fi
 
+# Create /etc/machine-id
 systemd-machine-id-setup
 
-if ! getent group systemd-journal >/dev/null; then
-    addgroup --system systemd-journal
-fi
+# Setup system users and groups
+addgroup --quiet --system systemd-journal
 
-if ! getent passwd systemd-timesync >/dev/null; then
-    adduser --system --group --no-create-home --home /run/systemd systemd-timesync
-fi
+adduser --quiet --system --group --no-create-home --home /run/systemd \
+    --gecos "systemd Time Synchronization" systemd-timesync
+adduser --quiet --system --group --no-create-home --home /run/systemd/netif \
+    --gecos "systemd Network Management" systemd-network
+adduser --quiet --system --group --no-create-home --home /run/systemd/resolve \
+    --gecos "systemd Resolver" systemd-resolve
+adduser --quiet --system --group --no-create-home --home /run/systemd \
+    --gecos "systemd Bus Proxy" systemd-bus-proxy
 
-if ! getent passwd systemd-network >/dev/null; then
-    adduser --system --group --no-create-home --home /run/systemd/netif systemd-network
-fi
-
-if ! getent passwd systemd-resolve >/dev/null; then
-    adduser --system --group --no-create-home --home /run/systemd/resolve systemd-resolve
-fi
-
-# initial update of the Message Catalogs database
+# Initial update of the Message Catalogs database
 _update_catalog
+
+# Make systemd-detect-virt utility usable for non-root users
+setcap cap_dac_override,cap_sys_ptrace=ep /usr/bin/systemd-detect-virt || true
 
 # We don’t ship /var/log/journal currently, so only run the following fix for
 # systems where the administrator has explicitly enabled persistent logging by
 # creating /var/log/journal.
 if [ -d /var/log/journal ]; then
-        # Grant read access to /var/log/journal for members of the adm group
-        # via a filesystem ACL. This makes them able to read the journal.
-        # Failure is ignored since there might be file systems mounted without
-        # ACL support.
-        setfacl -R -nm g:adm:rx,d:g:adm:rx /var/log/journal || true
+    # Grant read access to /var/log/journal for members of the adm group
+    # via a filesystem ACL. This makes them able to read the journal.
+    # Failure is ignored since there might be file systems mounted without
+    # ACL support.
+    setfacl -R -nm g:adm:rx,d:g:adm:rx /var/log/journal || true
 fi
-
-setcap cap_dac_override,cap_sys_ptrace=ep /usr/bin/systemd-detect-virt || true
 
 # Re-run systemctl enable for any service that was enabled when preinst was run.
 if dpkg --compare-versions "$2" ge "204"; then
     while read UNIT ; do
         systemctl enable $UNIT || true
     done </run/systemd/was-enabled || true
+fi
+
+if [ -n "$2" ]; then
+    _systemctl daemon-reexec || true
+    _systemctl try-restart systemd-journald.service || true
+    _systemctl try-restart systemd-logind.service || true
+    _systemctl try-restart systemd-networkd.service || true
+    _systemctl try-restart systemd-resolved.service || true
+    _systemctl try-restart systemd-timesyncd.service || true
 fi
 
 #DEBHELPER#
