Import patches-unapplied version 229-1ubuntu1 to ubuntu/xenial-proposed
Imported using git-ubuntu import.

Changelog parent: 272601a0862895058b4315413aa0c22485f729ca

New changelog entries:
  * Merge with Debian unstable. Remaining Ubuntu changes:
    - Hack to support system-image read-only /etc, and modify files in
      /etc/writable/ instead.
    Upgrade fixes, keep until 16.04 LTS release:
    - systemd Conflicts/Replaces/Provides systemd-services.
    - Remove obsolete systemd-logind upstart job.
    - Clean up obsolete /etc/udev/rules.d/README.
    - systemd.postinst: Migrate mountall specific fstab options to standard
      util-linux "nofail" option.
    - systemctl: Don't forward telinit u to upstart. This works around
      upstart's Restart() always reexec'ing /sbin/init on Restart(), even if
      that changes to point to systemd during the upgrade. This avoids running
      systemd during a dist-upgrade. (LP: #1430479)
    - Provide shutdown fallback for upstart. (LP: #1370329)
    - Break lvm (<< 2.02.133-1ubuntu1) and remove our dummy /etc/init.d/lvm2
      on upgrades, as it's shipped by lvm2 now.
    - Make udev break on mdadm << 3.3-2ubuntu3, as udev's init script dropped
      the "Provides: raid-mdadm".
    - Clean up /var/log/udev on upgrade (which is written under upstart, but
      not under systemd). (LP: #1537211)
    - Migrate existing s390x network configuration to new names. (LP: #1526808)
    - systemd.postinst: Bump Version comparison for migrating the UTC setting
      from /etc/default/rcS to /etc/adjtime, to run it for upgrades to 16.04.

diff --git a/debian/udev.postinst b/debian/udev.postinst
--- a/debian/udev.postinst
+++ b/debian/udev.postinst
@@ -88,6 +88,18 @@ Driver=virtio_net
 NamePolicy=onboard kernel
 EOF
   fi
+
+  # this is being written under upstart, but not under systemd; clean up
+  # obsolete files
+  if [ -d /run/systemd/system ]; then
+      rm -f /var/log/udev
+  fi
+
+  # transition existing interface names on s390x for #1526808
+  if dpkg --compare-versions "$2" lt-nl "228-4ubuntu2" &&
+      [ "$(dpkg --print-architecture)" = "s390x" ]; then
+    sed 's/enccw[0.]*/enc/' -i /etc/network/interfaces /etc/network/interfaces.d/* 2>/dev/null || true
+  fi
 }
 
 update_hwdb() {
